
INSERT INTO PATIENT.tb_PHONE_NUMBERS (PHONE_NUMBER_1) VALUES ('88232546')
INSERT INTO PATIENT.tb_PHONE_NUMBERS (PHONE_NUMBER_1) VALUES ('85462389')
INSERT INTO PATIENT.tb_PHONE_NUMBERS (PHONE_NUMBER_1) VALUES ('88232123')

SELECT* FROM PATIENT.tb_PHONE_NUMBERS
SELECT* FROM ADMINISTRATOR.tb_BLOOD

SELECT* FROM PATIENT.tb_PATIENT

INSERT INTO PATIENT.tb_PATIENT (ID_CARD,NAME,LAST_NAME,PASSWORD,AGE,BLOOD_ID,CIVIL_STATUS,ADDRESS,PHONE_NUMBERS_ID)
VALUES('4-0123-0876','Alberto','Castaño Segura','1',24,1,'Soltero','San José, San Pedro',5),
('7-0543-0189','María','Villa Mendez','2',28,1,'Soltera','Cervantes, Cartago',4)

-----------------------------

