CREATE PROCEDURE PATIENT.sp_LIST_PATIENT_ALLERGIES
@param_ID_CARD VARCHAR(32)
AS
BEGIN

SELECT
P.ID_CARD,
A.ALLERGY_TYPE,
P.NAME+' '+P.LAST_NAME AS full_name,
AP.DESCRIPTION,
AP.DIAGNOSTIC_DATE
	FROM PATIENT.tb_PATIENT P
	  JOIN PATIENT.tb_ALLERGY_PATIENT AP
		ON P.PATIENT_ID=AP.PATIENT_ID
		  JOIN ADMINISTRATOR.tb_ALLERGY A
		    ON A.ALLERGY_ID= AP.ALLERGY_ID
				WHERE P.ID_CARD=@param_ID_CARD AND AP.IS_DELETED=0
END

CREATE PROCEDURE PATIENT.sp_LIST_PATIENT_ALLERGY_MEDICAMENT
@param_ID_CARD VARCHAR(32),
@param_ALLERGY_TYPE VARCHAR(32)
AS
BEGIN
DECLARE @local_patient_id INT=
				(SELECT 
				PATIENT_ID 
					FROM PATIENT.tb_PATIENT 
						WHERE ID_CARD=@param_ID_CARD);

	DECLARE @local_allergy_id INT =
				(SELECT ALLERGY_ID 
					FROM ADMINISTRATOR.tb_ALLERGY 
						WHERE ALLERGY_TYPE=@param_ALLERGY_TYPE);

	SELECT
	M.MEDICINE_TYPE,
	P.ID_CARD,
	A.ALLERGY_TYPE
	FROM ADMINISTRATOR.tb_MEDICINE M
		JOIN PATIENT.tb_MEDICINE_ALLERGY_PATIENT MAP
		 ON M.MEDICINE_ID=MAP.MEDICINE_ID
			JOIN PATIENT.tb_PATIENT P
			 ON P.PATIENT_ID=MAP.PATIENT_ID
				JOIN ADMINISTRATOR.tb_ALLERGY A
					ON A.ALLERGY_ID=MAP.ALLERGY_ID
		  WHERE MAP.ALLERGY_ID=@local_allergy_id AND MAP.PATIENT_ID=@local_patient_id
END

ALTER PROCEDURE PATIENT.sp_REGISTER_PATIENT_ALLERGY
@param_ID_CARD VARCHAR(32),
@param_ALLERGY_TYPE VARCHAR(32),
@param_DESCRIPTION VARCHAR(200),
@param_DIAGNOSTIC_DATE DATE
AS
BEGIN
	IF NOT EXISTS (SELECT PATIENT_ID FROM PATIENT.tb_PATIENT WHERE ID_CARD=@param_ID_CARD)
		BEGIN
			RETURN -1;
		END

	DECLARE @local_patient_id INT=
				(SELECT 
				PATIENT_ID 
					FROM PATIENT.tb_PATIENT 
						WHERE ID_CARD=@param_ID_CARD);

	DECLARE @local_allergy_id INT =
				(SELECT ALLERGY_ID 
					FROM ADMINISTRATOR.tb_ALLERGY 
						WHERE ALLERGY_TYPE=@param_ALLERGY_TYPE);

	IF EXISTS (SELECT AP.PATIENT_ID,AP.ALLERGY_ID 
				FROM PATIENT.tb_ALLERGY_PATIENT AP 
					WHERE AP.ALLERGY_ID=@local_allergy_id 
						AND AP.PATIENT_ID=@local_patient_id AND AP.IS_DELETED=0)
		BEGIN
			RETURN 0;
		END
    ELSE IF EXISTS (SELECT AP.PATIENT_ID,AP.ALLERGY_ID 
				FROM PATIENT.tb_ALLERGY_PATIENT AP 
					WHERE AP.ALLERGY_ID=@local_allergy_id 
						AND AP.PATIENT_ID=@local_patient_id AND AP.IS_DELETED=1)
	    BEGIN
			UPDATE PATIENT.tb_ALLERGY_PATIENT 
				SET IS_DELETED=0, 
					DESCRIPTION=@param_DESCRIPTION, 
						DIAGNOSTIC_DATE=@param_DIAGNOSTIC_DATE
							WHERE ALLERGY_ID=@local_allergy_id 
									AND PATIENT_ID=@local_patient_id;
									RETURN 1;
	    END
	ELSE
		BEGIN
			INSERT INTO PATIENT.tb_ALLERGY_PATIENT 
			(PATIENT_ID,
			ALLERGY_ID,
			DIAGNOSTIC_DATE,
			DESCRIPTION)
			
			VALUES
			(
			 @local_patient_id,
			 @local_allergy_id,
			 @param_DIAGNOSTIC_DATE,
			 @param_DESCRIPTION
			);


			RETURN 1;
		END

END

CREATE PROCEDURE ADMINISTRATOR.sp_LIST_ALLERGY
AS
BEGIN
SELECT A.ALLERGY_TYPE FROM ADMINISTRATOR.tb_ALLERGY A
END

CREATE PROCEDURE PATIENT.sp_DELETE_PATIENT_ALERGY
@param_ID_CARD VARCHAR(32),
@param_ALLERGY_TYPE VARCHAR(32)
AS
BEGIN
	DECLARE @local_id_patient INT=(SELECT PATIENT_ID FROM PATIENT.tb_PATIENT WHERE ID_CARD=@param_ID_CARD);
	DECLARE @local_id_allergy INT=(SELECT ALLERGY_ID FROM ADMINISTRATOR.tb_ALLERGY WHERE ALLERGY_TYPE=@param_ALLERGY_TYPE);
	
	UPDATE PATIENT.tb_ALLERGY_PATIENT SET IS_DELETED=1 WHERE ALLERGY_ID=@local_id_allergy AND PATIENT_ID=@local_id_patient;
END


ALTER PROCEDURE PATIENT.sp_UPDATE_PATIENT_ALLERGY
@param_ID_CARD VARCHAR(32),
@param_OLD_ALLERGY_TYPE VARCHAR(32),
@param_ALLERGY_TYPE VARCHAR(32),
@param_DESCRIPTION VARCHAR(200),
@param_DIAGNOSTIC_DATE DATE
AS
BEGIN
	DECLARE @local_old_id_allergy INT=(SELECT ALLERGY_ID FROM ADMINISTRATOR.tb_ALLERGY WHERE ALLERGY_TYPE=@param_OLD_ALLERGY_TYPE);
	DECLARE @local_id_patient INT=(SELECT PATIENT_ID FROM PATIENT.tb_PATIENT WHERE ID_CARD=@param_ID_CARD);
	DECLARE @local_id_allergy INT=(SELECT ALLERGY_ID FROM ADMINISTRATOR.tb_ALLERGY WHERE ALLERGY_TYPE=@param_ALLERGY_TYPE);

	IF EXISTS (SELECT* FROM PATIENT.tb_ALLERGY_PATIENT WHERE PATIENT_ID=@local_id_patient AND ALLERGY_ID=@local_old_id_allergy)
	BEGIN
	 IF EXISTS (SELECT* FROM PATIENT.tb_ALLERGY_PATIENT WHERE PATIENT_ID=@local_id_patient AND ALLERGY_ID=@local_id_allergy AND @local_id_allergy!=@local_old_id_allergy)
	 BEGIN
	  RETURN -1;
	 END
	 ELSE IF(@local_old_id_allergy=@local_id_allergy)
	 BEGIN
	 UPDATE PATIENT.tb_ALLERGY_PATIENT 
			SET IS_DELETED=0,
			DESCRIPTION=@param_DESCRIPTION,
			DIAGNOSTIC_DATE=@param_DIAGNOSTIC_DATE
			WHERE PATIENT_ID=@local_id_patient AND ALLERGY_ID=@local_old_id_allergy;
			RETURN 1;
	 END
	 ELSE IF(@local_old_id_allergy!=@local_id_allergy)
	 BEGIN
	 UPDATE PATIENT.tb_ALLERGY_PATIENT 
			SET IS_DELETED=0,
			ALLERGY_ID=@local_id_allergy,
			DESCRIPTION=@param_DESCRIPTION,
			DIAGNOSTIC_DATE=@param_DIAGNOSTIC_DATE
			WHERE PATIENT_ID=@local_id_patient AND ALLERGY_ID=@local_id_allergy;
			RETURN 1;
	 END
	 END
	
END

CREATE PROCEDURE ADMINISTRATOR.sp_LIST_MEDICINE
AS
BEGIN
SELECT MEDICINE_TYPE FROM ADMINISTRATOR.tb_MEDICINE
END

CREATE PROCEDURE PATIENT.sp_LIST_PATIENT_MEDICAMENT
@param_ID_CARD VARCHAR(32),
@param_ALLERGY_TYPE VARCHAR(32)
AS
BEGIN
	DECLARE @local_id_allergy INT=(SELECT ALLERGY_ID FROM ADMINISTRATOR.tb_ALLERGY WHERE ALLERGY_TYPE=@param_ALLERGY_TYPE);
	DECLARE @local_id_patient INT=(SELECT PATIENT_ID FROM PATIENT.tb_PATIENT WHERE ID_CARD=@param_ID_CARD);
	
	SELECT
	M.MEDICINE_TYPE
	FROM PATIENT.tb_MEDICINE_ALLERGY_PATIENT MAP
	JOIN ADMINISTRATOR.tb_MEDICINE M
	ON M.MEDICINE_ID=MAP.MEDICINE_ID
	WHERE MAP.PATIENT_ID=@local_id_patient 
	AND MAP.ALLERGY_ID=@local_id_allergy 
	AND MAP.IS_DELETED=0;

END

CREATE PROCEDURE PATIENT.sp_ADD_PACIENT_MEDICAMENT
@param_ID_CARD VARCHAR(32),
@param_ALLERGY_TYPE VARCHAR(32),
@param_MEDICINE_TYPE VARCHAR(32)
AS
BEGIN
	DECLARE @local_id_allergy INT=(SELECT ALLERGY_ID FROM ADMINISTRATOR.tb_ALLERGY WHERE ALLERGY_TYPE=@param_ALLERGY_TYPE);
	DECLARE @local_id_patient INT=(SELECT PATIENT_ID FROM PATIENT.tb_PATIENT WHERE ID_CARD=@param_ID_CARD);
	DECLARE @local_id_medicine INT=(SELECT MEDICINE_ID FROM ADMINISTRATOR.tb_MEDICINE WHERE MEDICINE_TYPE=@param_MEDICINE_TYPE);

	IF EXISTS (SELECT* 
		FROM PATIENT.tb_MEDICINE_ALLERGY_PATIENT
			WHERE PATIENT_ID=@local_id_patient 
				AND MEDICINE_ID=@local_id_medicine 
					AND ALLERGY_ID=@local_id_allergy)
		BEGIN
			UPDATE  PATIENT.tb_MEDICINE_ALLERGY_PATIENT 
					SET IS_DELETED=0 
						WHERE PATIENT_ID=@local_id_patient 
							AND MEDICINE_ID=@local_id_medicine 
								AND ALLERGY_ID=@local_id_allergy;
		END
	ELSE
		BEGIN
			INSERT INTO PATIENT.tb_MEDICINE_ALLERGY_PATIENT 
			(MEDICINE_ID,
			PATIENT_ID,
			ALLERGY_ID) 
			VALUES (@local_id_medicine, @local_id_patient,@local_id_allergy);
		END

END


CREATE PROCEDURE PATIENT.REMOVE_PATIENT_MEDICAMENT
@param_ID_CARD VARCHAR(32),
@param_ALLERGY_TYPE VARCHAR(32),
@param_MEDICINE_TYPE VARCHAR(32)
AS
BEGIN
	DECLARE @local_id_allergy INT=(SELECT ALLERGY_ID FROM ADMINISTRATOR.tb_ALLERGY WHERE ALLERGY_TYPE=@param_ALLERGY_TYPE);
	DECLARE @local_id_patient INT=(SELECT PATIENT_ID FROM PATIENT.tb_PATIENT WHERE ID_CARD=@param_ID_CARD);
	DECLARE @local_id_medicine INT=(SELECT MEDICINE_ID FROM ADMINISTRATOR.tb_MEDICINE WHERE MEDICINE_TYPE=@param_MEDICINE_TYPE);

	UPDATE PATIENT.tb_MEDICINE_ALLERGY_PATIENT 
	SET IS_DELETED=1 
	WHERE PATIENT_ID=@local_id_patient 
	AND MEDICINE_ID=@local_id_medicine
	AND ALLERGY_ID=@local_id_allergy;


END





