CREATE PROCEDURE PATIENT.sp_LIST_PATIENT_ALLERGIES
@param_ID_CARD VARCHAR(32)
AS
BEGIN

SELECT
P.ID_CARD,
A.ALLERGY_TYPE,
P.NAME+' '+P.LAST_NAME AS full_name,
AP.DESCRIPTION,
AP.DIAGNOSTIC_DATE
	FROM PATIENT.tb_PATIENT P
	  JOIN PATIENT.tb_ALLERGY_PATIENT AP
		ON P.PATIENT_ID=AP.PATIENT_ID
		  JOIN ADMINISTRATOR.tb_ALLERGY A
		    ON A.ALLERGY_ID= AP.ALLERGY_ID
				WHERE P.ID_CARD=@param_ID_CARD AND AP.IS_DELETED=0
END

CREATE PROCEDURE PATIENT.sp_LIST_PATIENT_ALLERGY_MEDICAMENT
@param_ID_CARD VARCHAR(32),
@param_ALLERGY_TYPE VARCHAR(32)
AS
BEGIN
DECLARE @local_patient_id INT=
				(SELECT 
				PATIENT_ID 
					FROM PATIENT.tb_PATIENT 
						WHERE ID_CARD=@param_ID_CARD);

	DECLARE @local_allergy_id INT =
				(SELECT ALLERGY_ID 
					FROM ADMINISTRATOR.tb_ALLERGY 
						WHERE ALLERGY_TYPE=@param_ALLERGY_TYPE);

	SELECT
	M.MEDICINE_TYPE,
	P.ID_CARD,
	A.ALLERGY_TYPE
	FROM ADMINISTRATOR.tb_MEDICINE M
		JOIN PATIENT.tb_MEDICINE_ALLERGY_PATIENT MAP
		 ON M.MEDICINE_ID=MAP.MEDICINE_ID
			JOIN PATIENT.tb_PATIENT P
			 ON P.PATIENT_ID=MAP.PATIENT_ID
				JOIN ADMINISTRATOR.tb_ALLERGY A
					ON A.ALLERGY_ID=MAP.ALLERGY_ID
		  WHERE MAP.ALLERGY_ID=@local_allergy_id AND MAP.PATIENT_ID=@local_patient_id
END





CREATE PROCEDURE PATIENT.sp_REGISTER_PATIENT_ALLERGY
@param_ID_CARD VARCHAR(32),
@param_ALLERGY_TYPE VARCHAR(32),
@param_DESCRIPTION VARCHAR(200),
@param_DIAGNOSTIC_DATE DATE
AS
BEGIN
	DECLARE @local_patient_id INT=
				(SELECT 
				PATIENT_ID 
					FROM PATIENT.tb_PATIENT 
						WHERE ID_CARD=@param_ID_CARD);

	DECLARE @local_allergy_id INT =
				(SELECT ALLERGY_ID 
					FROM ADMINISTRATOR.tb_ALLERGY 
						WHERE ALLERGY_TYPE=@param_ALLERGY_TYPE);

	IF EXISTS (SELECT AP.PATIENT_ID,AP.ALLERGY_ID 
				FROM PATIENT.tb_ALLERGY_PATIENT AP 
					WHERE AP.ALLERGY_ID=@local_allergy_id 
						AND AP.PATIENT_ID=@local_patient_id AND AP.IS_DELETED=0)
		BEGIN
			RETURN 0;
		END
    ELSE IF EXISTS (SELECT AP.PATIENT_ID,AP.ALLERGY_ID 
				FROM PATIENT.tb_ALLERGY_PATIENT AP 
					WHERE AP.ALLERGY_ID=@local_allergy_id 
						AND AP.PATIENT_ID=@local_patient_id AND AP.IS_DELETED=1)
	    BEGIN
			UPDATE PATIENT.tb_ALLERGY_PATIENT 
				SET IS_DELETED=0, 
					DESCRIPTION=@param_DESCRIPTION, 
						DIAGNOSTIC_DATE=@param_DIAGNOSTIC_DATE
							WHERE ALLERGY_ID=@local_allergy_id 
									AND PATIENT_ID=@local_patient_id
	    END
	ELSE
		BEGIN
			INSERT INTO PATIENT.tb_ALLERGY_PATIENT 
			(PATIENT_ID,
			ALLERGY_ID,
			DIAGNOSTIC_DATE,
			DESCRIPTION)
			
			VALUES
			(
			 @local_patient_id,
			 @local_allergy_id,
			 @param_DIAGNOSTIC_DATE,
			 @param_DESCRIPTION
			);


			RETURN 1;
		END

END







