
CREATE PROCEDURE ADMINISTRATOR.sp_REGISTER_VACCINATION
@param_ID_CARD VARCHAR(32),
@param_VACCINE_TYPE VARCHAR(32),
@param_DESCRIPTION VARCHAR(200) NULL,
@param_LATTEST_VACCINE_DATE DATE,
@param_NEXT_VACCINE_DATE DATE
AS
BEGIN

	IF NOT EXISTS (SELECT ID_CARD FROM PATIENT.tb_PATIENT WHERE ID_CARD=@param_ID_CARD)
		BEGIN
			RETURN -1;
		END
	ELSE
		BEGIN
			DECLARE @local_patient_id INT=
			(SELECT 
			PATIENT_ID 
				FROM PATIENT.tb_PATIENT 
					WHERE ID_CARD=@param_ID_CARD);

			DECLARE @local_vaccine_id INT=
			(SELECT VACCINE_ID 
				FROM ADMINISTRATOR.tb_VACCINE
					WHERE VACCINE_TYPE=@param_VACCINE_TYPE);

			IF EXISTS (SELECT PATIENT_ID, VACCINE_ID FROM PATIENT.tb_VACCINE_PATIENT WHERE PATIENT_ID=@local_patient_id AND VACCINE_ID=@local_vaccine_id AND IS_DELETED=0)
				BEGIN
					RETURN 0;
				END
			ELSE IF EXISTS (SELECT PATIENT_ID, VACCINE_ID FROM PATIENT.tb_VACCINE_PATIENT WHERE PATIENT_ID=@local_patient_id AND VACCINE_ID=@local_vaccine_id AND IS_DELETED=1)
				BEGIN
					UPDATE PATIENT.tb_VACCINE_PATIENT 
					SET IS_DELETED=0, 
					DESCRIPTION=@param_DESCRIPTION, 
					LATTEST_VACCINE_DATE=@param_LATTEST_VACCINE_DATE,
					NEXT_VACCINE_DATE=@param_NEXT_VACCINE_DATE
					WHERE PATIENT_ID=@local_patient_id AND VACCINE_ID=@local_vaccine_id;
				END

			ELSE
				BEGIN

				

					INSERT INTO PATIENT.tb_VACCINE_PATIENT 
						(PATIENT_ID,
						VACCINE_ID,
						DESCRIPTION, 
						LATTEST_VACCINE_DATE,
						NEXT_VACCINE_DATE
						) 
						VALUES 
						(@local_patient_id,
						@local_vaccine_id,
						@param_DESCRIPTION,
						@param_LATTEST_VACCINE_DATE,
						@param_NEXT_VACCINE_DATE);

						
				END
		RETURN 1;
	   END
END



CREATE PROCEDURE ADMINISTRATOR.sp_LIST_PATIENT_VACCINE
@param_ID_CARD VARCHAR(32)
AS
BEGIN

SELECT

V.VACCINE_TYPE,
(P.NAME+' '+P.LAST_NAME) AS full_name,
VP.DESCRIPTION,
VP.LATTEST_VACCINE_DATE,
VP.NEXT_VACCINE_DATE

	FROM ADMINISTRATOR.tb_VACCINE V
      JOIN PATIENT.tb_VACCINE_PATIENT VP
        ON V.VACCINE_ID=VP.VACCINE_ID
         JOIN PATIENT.tb_PATIENT P
			ON P.PATIENT_ID=VP.PATIENT_ID
			 WHERE P.ID_CARD=@param_ID_CARD AND VP.IS_DELETED=0

END

CREATE PROCEDURE ADMINISTRATOR.sp_LIST_VACCINE
AS
BEGIN
SELECT
V.VACCINE_TYPE
FROM ADMINISTRATOR.tb_VACCINE V
END


CREATE PROCEDURE PATIENT.sp_DELETE_PATIENT_VACCINE
@param_ID_CARD VARCHAR(32),
@param_VACCINATION_TYPE VARCHAR(32)
AS
BEGIN
DECLARE @local_id_patient INT=(SELECT PATIENT_ID FROM PATIENT.tb_PATIENT WHERE ID_CARD=@param_ID_CARD);
	UPDATE PATIENT.tb_VACCINE_PATIENT SET IS_DELETED=1 WHERE PATIENT_ID=@local_id_patient;
END


CREATE PROCEDURE PATIENT.sp_UPDATE_PATIENT_VACCINE
@param_ID_CARD VARCHAR(32),
@param_VACCINE_TYPE VARCHAR(32),
@param_DESCRIPTION VARCHAR(200) NULL,
@param_LATTEST_VACCINE_DATE DATE,
@param_NEXT_VACCINE_DATE DATE
AS
BEGIN
DECLARE @local_patient_id INT=(SELECT PATIENT_ID FROM PATIENT.tb_PATIENT WHERE ID_CARD=@param_ID_CARD);
DECLARE @local_vaccine_id INT=(SELECT VACCINE_TYPE FROM ADMINISTRATOR.tb_VACCINE WHERE VACCINE_TYPE=@param_VACCINE_TYPE);

UPDATE PATIENT.tb_VACCINE_PATIENT 
SET VACCINE_ID=@local_vaccine_id, 
DESCRIPTION=@param_DESCRIPTION,
LATTEST_VACCINE_DATE=@param_LATTEST_VACCINE_DATE, 
NEXT_VACCINE_DATE=@param_NEXT_VACCINE_DATE
WHERE PATIENT_ID=@local_patient_id;

END